import compression from 'compression';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import pinoHttp from 'pino-http';
import { env } from './config/env.js';
import { errorHandler, notFoundHandler } from './middleware/errors.js';
import { authRoutes } from './routes/authRoutes.js';
import { orderRoutes } from './routes/orderRoutes.js';
import { automationRoutes } from './routes/automationRoutes.js';
import { assign, assignSchema, location, locationSchema } from './controllers/automationController.js';
import { authenticate, requireRoles } from './middleware/auth.js';
import { requireWebhookSecret } from './middleware/webhookAuth.js';
import { validateBody } from './middleware/validate.js';

export const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((origin) => origin.trim()), credentials: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use(compression());
app.use(pinoHttp());
app.use(express.json({ limit: '1mb' }));
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use('/api/v1/auth', authRoutes);
app.patch('/api/v1/orders/:orderId/assign', requireWebhookSecret, validateBody(assignSchema), assign);
app.use('/api/v1/orders', orderRoutes);
app.use('/api/v1/automation', automationRoutes);
app.post('/api/v1/drivers/location', authenticate, requireRoles('driver'), validateBody(locationSchema), location);
app.use(notFoundHandler);
app.use(errorHandler);
